# This file provides instructions for packaging.

@prefix : <http://ontologi.es/doap-deps#>.

`Regexp-Util`
	:runtime-requirement  [ :on "perl 5.010"^^:CpanId ];
	:test-requirement     [ :on "Test::More 0.92"^^:CpanId ].

